cljsc warnings, update deps & test runners
replikativ/superv.async pull request #16
Opened 2022-11-05 20:56 UTC by pkpkpk

clears some warnings in cljs, added testing one-liners to deps.edn

2022-11-08 04:06 UTC, whilo approved these changes
Thanks a lot!

2022-11-16 15:08 UTC, TimoKramer commented
Hi @pkpkpk. Thanks for this PR. Were you able to run the ./bin/run-cljstests? It does not work for me.

2022-11-16 16:09 UTC, TimoKramer requested changes
Thanks for putting in the effort. I don't know why the test-supervisor test is failing in cljs but maybe you can find the issue ;) 👍

2022-11-16 16:09 UTC, TimoKramer commented on deps.edn
>   :aliases {:cljs   {:extra-deps  {thheller/shadow-cljs {:mvn/version "2.17.2"}
I think the version of shadow-cljs has to match the clojurescript version. Can you please update all the deps at once? I am using [neil ](https://github.com/babashka/neil) for it, it's awesome.

2022-11-16 16:09 UTC, TimoKramer commented on test/superv/node_runner.cljs
> +(set! *main-cli-fn* -main)
Do you think it is necessary to have this? In theory node tests should run with `https://github.com/babashka/neil`. I am not really familiar with cljs so I am just asking.

2022-11-16 16:09 UTC, TimoKramer commented on deps.edn
> +                      :exec-fn cognitect.test-runner.api/test}
Did you see the `bin/run-unittests` script? We are using these to have a simplified CI. Does that script do what you are trying to accomplish? If not we would need to run these tests here in the script as well.

2022-11-16 16:09 UTC, TimoKramer commented on deps.edn
> +                       :main-opts ["-m" "cljs.main" "-t" "node" "-m" "superv.node-runner"]}
Did you see the `bin/run-cljstests` script? I know it is not running the node-tests atm. But when you uncomment https://github.com/replikativ/superv.async/blob/main/test/superv/async_test.cljc#L332 you should be able to run the node-tests from the script again and this part here would not be necessary.

2022-11-16 16:12 UTC, TimoKramer commented on deps.edn
> +                       :main-opts ["-m" "cljs.main" "-t" "node" "-m" "superv.node-runner"]}
Then our pipeline for superv.async looks better again. That would be ace!

2022-11-16 18:44 UTC, pkpkpk commented
I will take a deeper look at this in a week or so I am afk for now. I have no knowledge of shadow cljs, I use the compiler manually. I will change it how you see fit, was just trying clear the warnings 👍

2023-02-15 15:18 UTC, TimoKramer approved these changes

2023-02-15 15:18 UTC, merged